import type { Metadata } from 'next'
import { Arvo } from 'next/font/google'
import './globals.css'

const arvo = Arvo({
  weight: ['400', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={arvo.className}>{children}</body>
    </html>
  )
}
